services:
  db:
    image: postgres:15
    container_name: syslack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: syslack
      POSTGRES_USER: syslack
      POSTGRES_PASSWORD: syslack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: nest-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "4000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: next-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
