services:
  db:
    image: postgres:15
    container_name: syslack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: syslack
      POSTGRES_USER: syslack
      POSTGRES_PASSWORD: syslack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
